apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miamo-ingress
  namespace: miamo
  labels:
    app: miamo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 3200
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 3200
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3100
