#!/usr/bin/env python3
"""Write the updated settings page."""
import os

SETTINGS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    'services', 'web', 'src', 'app', '(main)', 'settings', 'page.tsx'
)

lines = []
def L(s=''):
    lines.append(s)

L("'use client';")
L()
L("import { useState, useEffect, useCallback } from 'react';")
L("import { motion, AnimatePresence } from 'framer-motion';")
L("import { User, Shield, Bell, Palette, Lock, Globe, Moon, Sun, Monitor, Trash2, Download, LogOut, Check as CheckIcon, Copy, KeyRound, Wifi, X } from 'lucide-react';")
L("import { Button } from '@/components/ui/button';")
L("import { Card } from '@/components/ui';")
L("import { SettingsSkeleton } from '@/components/ui/skeleton';")
L("import { InputModal, PasswordModal, Toast } from '@/components/ui/modal';")
L("import { cn } from '@/lib/utils';")
L("import { api } from '@/lib/api';")
L("import { useAuthStore, useThemeStore } from '@/stores';")
L("import { useRouter } from 'next/navigation';")
L()
L("interface ToggleProps { enabled: boolean; onToggle: () => void; }")
L("function Toggle({ enabled, onToggle }: ToggleProps) {")
L("  return (")
L("    <button onClick={onToggle} className={cn('w-10 h-6 rounded-full transition-colors relative', enabled ? 'bg-lavender-400' : 'bg-miamo-elevated border border-border')}>")
L("      <motion.div animate={{ x: enabled ? 18 : 2 }} className=\"absolute top-1 w-4 h-4 rounded-full bg-white shadow\" />")
L("    </button>")
L("  );")
L("}")
L()
L("interface SettingRowProps { label: string; description?: string; children: React.ReactNode; }")
L("function SettingRow({ label, description, children }: SettingRowProps) {")
L("  return (")
L("    <div className=\"flex items-center justify-between py-3 border-b border-border/30 last:border-0\">")
L("      <div className=\"flex-1 min-w-0 pr-4\">")
L("        <p className=\"text-sm text-text-primary\">{label}</p>")
L("        {description && <p className=\"text-xs text-text-muted mt-0.5\">{description}</p>}")
L("      </div>")
L("      {children}")
L("    </div>")
L("  );")
L("}")
L()

# TwoFactorModal
L("function TwoFactorModal({ open, onClose }: { open: boolean; onClose: () => void }) {")
L("  if (!open) return null;")
L("  return (")
L("    <>")
L("      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className=\"fixed inset-0 bg-black/60 backdrop-blur-sm z-50\" onClick={onClose} />")
L("      <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}")
L("        className=\"fixed inset-x-4 top-[20%] max-w-sm mx-auto bg-miamo-card border border-border rounded-2xl shadow-2xl z-50 p-6 text-center\">")
L("        <div className=\"w-14 h-14 rounded-2xl bg-lavender-400/10 flex items-center justify-center mx-auto mb-4\">")
L("          <KeyRound className=\"w-7 h-7 text-lavender-400\" />")
L("        </div>")
L("        <h3 className=\"text-base font-bold text-text-primary mb-2\">Two-Factor Authentication</h3>")
L("        <p className=\"text-sm text-text-muted mb-2\">Protect your account with an extra layer of security.</p>")
L("        <div className=\"bg-miamo-elevated rounded-xl p-4 mb-4 border border-border/30\">")
L("          <div className=\"w-32 h-32 bg-miamo-card rounded-xl mx-auto mb-2 flex items-center justify-center border border-border/50\">")
L("            <KeyRound className=\"w-8 h-8 text-text-muted/30\" />")
L("          </div>")
L("          <p className=\"text-xs text-text-muted\">Scan with your authenticator app</p>")
L("        </div>")
L("        <div className=\"bg-amber-500/10 border border-amber-500/20 rounded-xl p-3 mb-4\">")
L("          <p className=\"text-xs text-amber-400 font-medium\">Coming in the next update</p>")
L("        </div>")
L("        <Button variant=\"secondary\" size=\"sm\" onClick={onClose} className=\"w-full\">Got it</Button>")
L("      </motion.div>")
L("    </>")
L("  );")
L("}")
L()

# SessionsModal
L("function SessionsModal({ open, onClose }: { open: boolean; onClose: () => void }) {")
L("  if (!open) return null;")
L("  return (")
L("    <>")
L("      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className=\"fixed inset-0 bg-black/60 backdrop-blur-sm z-50\" onClick={onClose} />")
L("      <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}")
L("        className=\"fixed inset-x-4 top-[15%] max-w-md mx-auto bg-miamo-card border border-border rounded-2xl shadow-2xl z-50 overflow-hidden\">")
L("        <div className=\"flex items-center justify-between px-5 py-4 border-b border-border/30\">")
L("          <h3 className=\"text-sm font-bold text-text-primary\">Active Sessions</h3>")
L("          <button onClick={onClose}><X className=\"w-4 h-4 text-text-muted\" /></button>")
L("        </div>")
L("        <div className=\"p-5 space-y-3\">")
L("          <div className=\"flex items-center gap-3 p-3 bg-emerald-500/5 border border-emerald-500/20 rounded-xl\">")
L("            <Wifi className=\"w-5 h-5 text-emerald-400\" />")
L("            <div className=\"flex-1\">")
L("              <p className=\"text-sm font-medium text-text-primary\">Current Browser</p>")
L("              <p className=\"text-xs text-text-muted\">Active now</p>")
L("            </div>")
L("            <span className=\"text-[10px] font-medium text-emerald-400 bg-emerald-500/10 px-2 py-1 rounded-full\">Active</span>")
L("          </div>")
L("          <p className=\"text-xs text-text-muted text-center py-2\">No other active sessions.</p>")
L("          <Button variant=\"secondary\" size=\"sm\" onClick={onClose} className=\"w-full\">Close</Button>")
L("        </div>")
L("      </motion.div>")
L("    </>")
L("  );")
L("}")
L()

# Sections
L("const sections = [")
L("  { id: 'account', label: 'Account', icon: User },")
L("  { id: 'privacy', label: 'Privacy & Search', icon: Shield },")
L("  { id: 'notifications', label: 'Notifications', icon: Bell },")
L("  { id: 'appearance', label: 'Appearance', icon: Palette },")
L("  { id: 'preferences', label: 'Preferences', icon: Globe },")
L("  { id: 'safety', label: 'Safety', icon: Lock },")
L("  { id: 'data', label: 'Data & Account', icon: Globe },")
L("];")
L()

# Main component
L("export default function SettingsPage() {")
L("  const router = useRouter();")
L("  const { clearAuth, user } = useAuthStore();")
L("  const { theme, setTheme } = useThemeStore();")
L("  const [activeSection, setActiveSection] = useState('account');")
L("  const [loading, setLoading] = useState(true);")
L("  const [saved, setSaved] = useState(false);")
L("  const [downloading, setDownloading] = useState(false);")
L("  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);")
L("  const [blockList, setBlockList] = useState<any[]>([]);")
L("  const [copiedId, setCopiedId] = useState(false);")
L("  const [emailModal, setEmailModal] = useState(false);")
L("  const [passwordModal, setPasswordModal] = useState(false);")
L("  const [passwordError, setPasswordError] = useState('');")
L("  const [phoneModal, setPhoneModal] = useState(false);")
L("  const [twoFactorModal, setTwoFactorModal] = useState(false);")
L("  const [sessionsModal, setSessionsModal] = useState(false);")
L("  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' | 'info'; open: boolean }>({ message: '', type: 'info', open: false });")
L("  const showToast = useCallback((message: string, type: 'success' | 'error' | 'info' = 'info') => { setToast({ message, type, open: true }); }, []);")
L()
L("  const [settings, setSettings] = useState({")
L("    searchByName: true, searchByMiamoId: true, searchByCity: false,")
L("    onlineStatus: true, lastActive: true, readReceipts: true, typingIndicator: true,")
L("    matchNotifications: true, messageNotifications: true, beatReminders: true,")
L("    storyNotifications: false, quietHours: false, reduceMotion: false,")
L("    disappearingMessages: false, seriousMode: false, broadcastReceive: true, aiPersonalization: true,")
L("    profileVisibility: 'public' as string, language: 'English', fontSize: 'medium' as string,")
L("    notificationSound: true, autoplayVideos: true, chatBubbleStyle: 'modern' as string, dateFormat: 'relative' as string,")
L("  });")
L()

# useEffect for loading settings
L("  useEffect(() => {")
L("    api.getSettings().then(res => {")
L("      if (res.data) {")
L("        const s = res.data; const p = s.privacy || {};")
L("        setSettings(prev => ({ ...prev,")
L("          searchByName: p.searchByName ?? prev.searchByName, onlineStatus: p.onlineStatus ?? prev.onlineStatus,")
L("          readReceipts: p.readReceipts ?? prev.readReceipts,")
L("          matchNotifications: s.notifications?.matches ?? prev.matchNotifications,")
L("          messageNotifications: s.notifications?.messages ?? prev.messageNotifications,")
L("          beatReminders: s.notifications?.beats ?? prev.beatReminders,")
L("          storyNotifications: s.notifications?.stories ?? prev.storyNotifications,")
L("          profileVisibility: p.profileVisibility ?? prev.profileVisibility,")
L("          language: s.preferences?.language ?? prev.language, fontSize: s.preferences?.fontSize ?? prev.fontSize,")
L("          notificationSound: s.preferences?.notificationSound ?? prev.notificationSound,")
L("          autoplayVideos: s.preferences?.autoplayVideos ?? prev.autoplayVideos,")
L("          chatBubbleStyle: s.preferences?.chatBubbleStyle ?? prev.chatBubbleStyle,")
L("          dateFormat: s.preferences?.dateFormat ?? prev.dateFormat,")
L("        }));")
L("      }")
L("    }).catch(() => {}).finally(() => setLoading(false));")
L("  }, []);")
L()

# toggle function
L("  const toggle = async (key: keyof typeof settings) => {")
L("    const newVal = !settings[key]; setSettings(s => ({ ...s, [key]: newVal }));")
L("    try {")
L("      const privacyKeys = ['searchByName','searchByMiamoId','searchByCity','onlineStatus','lastActive','readReceipts','typingIndicator','disappearingMessages','seriousMode','broadcastReceive','aiPersonalization'];")
L("      const notifKeys = ['matchNotifications','messageNotifications','beatReminders','storyNotifications'];")
L("      if (privacyKeys.includes(key)) await api.updatePrivacy({ [key]: newVal });")
L("      else if (notifKeys.includes(key)) { const m: Record<string,string> = { matchNotifications:'matches', messageNotifications:'messages', beatReminders:'beats', storyNotifications:'stories' }; await api.updateSettings({ notifications: { [m[key]]: newVal } }); }")
L("      else if (['notificationSound','autoplayVideos'].includes(key)) await api.updateSettings({ preferences: { [key]: newVal } });")
L("      setSaved(true); setTimeout(() => setSaved(false), 1500);")
L("    } catch { setSettings(s => ({ ...s, [key]: !newVal })); }")
L("  };")
L()

# updatePref function
L("  const updatePref = async (key: string, value: string) => {")
L("    setSettings(s => ({ ...s, [key]: value }));")
L("    try {")
L("      if (key === 'profileVisibility') await api.updatePrivacy({ profileVisibility: value });")
L("      else await api.updateSettings({ preferences: { [key]: value } });")
L("      setSaved(true); setTimeout(() => setSaved(false), 1500);")
L("    } catch { showToast('Failed to save', 'error'); }")
L("  };")
L()

# helper functions
L("  const copyMiamoId = () => {")
L("    if (user?.username) navigator.clipboard?.writeText(user.username).then(() => {")
L("      setCopiedId(true); showToast('Miamo ID copied!', 'success'); setTimeout(() => setCopiedId(false), 2000);")
L("    });")
L("  };")
L()
L("  const handleDownload = async () => {")
L("    setDownloading(true);")
L("    try {")
L("      const res = await api.exportData();")
L("      const blob = new Blob([JSON.stringify(res.data || res, null, 2)], { type: 'application/json' });")
L("      const url = URL.createObjectURL(blob); const a = document.createElement('a');")
L("      a.href = url; a.download = 'miamo-data-export.json'; a.click(); URL.revokeObjectURL(url);")
L("      showToast('Data exported', 'success');")
L("    } catch { showToast('Export failed', 'error'); }")
L("    setDownloading(false);")
L("  };")
L()
L("  const handleDeactivate = async () => { try { await api.deactivateAccount(); clearAuth(); router.push('/login'); } catch { showToast('Failed', 'error'); } };")
L("  const handleLogout = async () => { try { await api.logout(); } catch {} clearAuth(); router.push('/login'); };")
L("  const handleUnblock = async (userId: string) => { try { await api.unblockUser(userId); setBlockList(prev => prev.filter(b => b.id !== userId)); showToast('Unblocked', 'success'); } catch {} };")
L("  const loadBlockList = () => { api.getBlockList().then(res => setBlockList(res.data || [])).catch(() => {}); };")
L()

# JSX return
L("  return (")
L("    <div className=\"max-w-4xl mx-auto p-6\">")
L("      <Toast message={toast.message} type={toast.type} open={toast.open} onClose={() => setToast(t => ({...t, open: false}))} />")
L("      <InputModal open={emailModal} onClose={() => setEmailModal(false)} title=\"Change Email\" label=\"New email\" defaultValue={user?.email||''} placeholder=\"you@example.com\" type=\"email\" onSubmit={async v => { try { await api.updateProfile({email:v}); showToast('Email updated','success'); } catch { showToast('Failed','error'); } }} submitLabel=\"Update Email\" />")
L("      <InputModal open={phoneModal} onClose={() => setPhoneModal(false)} title=\"Add Phone\" label=\"Phone number\" placeholder=\"+1 (555) 000-0000\" type=\"tel\" onSubmit={async v => { try { await api.updateProfile({phone:v}); showToast('Phone added','success'); } catch { showToast('Failed','error'); } }} submitLabel=\"Save\" />")
L("      <PasswordModal open={passwordModal} onClose={() => { setPasswordModal(false); setPasswordError(''); }} error={passwordError} onSubmit={async (cur,pw) => { try { await api.updatePassword({currentPassword:cur,newPassword:pw}); setPasswordModal(false); showToast('Password updated','success'); } catch { setPasswordError('Failed'); } }} />")
L("      <TwoFactorModal open={twoFactorModal} onClose={() => setTwoFactorModal(false)} />")
L("      <SessionsModal open={sessionsModal} onClose={() => setSessionsModal(false)} />")
L()
L("      {loading ? <SettingsSkeleton /> : (<>")
L("      <div className=\"flex items-center justify-between mb-6\">")
L("        <h1 className=\"text-xl font-bold\">Settings</h1>")
L("        <div className=\"flex items-center gap-2\">")
L("          {saved && <span className=\"text-xs text-emerald-400 flex items-center gap-1\"><CheckIcon className=\"w-3 h-3\" /> Saved</span>}")
L("          <Button variant=\"danger\" size=\"sm\" onClick={handleLogout}><LogOut className=\"w-3.5 h-3.5\" /> Sign Out</Button>")
L("        </div>")
L("      </div>")
L()
L("      <div className=\"grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-6\">")
L("        <nav className=\"flex lg:flex-col gap-1 overflow-x-auto lg:overflow-visible no-scrollbar\">")
L("          {sections.map(s => (")
L("            <button key={s.id} onClick={() => setActiveSection(s.id)} className={cn('flex items-center gap-2.5 px-3 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap transition-all', activeSection === s.id ? 'bg-lavender-400/10 text-lavender-400' : 'text-text-muted hover:text-text-secondary hover:bg-miamo-elevated/50')}>")
L("              <s.icon className=\"w-4 h-4\" /> {s.label}")
L("            </button>")
L("          ))}")
L("        </nav>")
L()
L("        <Card className=\"p-6\">")

# Account section
L("          {activeSection === 'account' && (")
L("            <div className=\"space-y-1\">")
L("              <h2 className=\"text-base font-semibold mb-4\">Account</h2>")
L("              <SettingRow label=\"Email\" description={user?.email || 'Not set'}><Button variant=\"ghost\" size=\"sm\" onClick={() => setEmailModal(true)}>Change</Button></SettingRow>")
L("              <SettingRow label=\"Password\" description=\"Last changed 30 days ago\"><Button variant=\"ghost\" size=\"sm\" onClick={() => setPasswordModal(true)}>Update</Button></SettingRow>")
L("              <SettingRow label=\"Miamo ID\" description={`@${user?.username || 'user'} \\u2014 System-generated, read-only`}><Button variant=\"ghost\" size=\"sm\" onClick={copyMiamoId}>{copiedId ? <><CheckIcon className=\"w-3.5 h-3.5 text-emerald-400\" /> Copied</> : <><Copy className=\"w-3.5 h-3.5\" /> Copy ID</>}</Button></SettingRow>")
L("              <SettingRow label=\"Phone\" description=\"Not set\"><Button variant=\"ghost\" size=\"sm\" onClick={() => setPhoneModal(true)}>Add</Button></SettingRow>")
L("              <SettingRow label=\"Two-factor authentication\" description=\"Add extra security\"><Button variant=\"ghost\" size=\"sm\" onClick={() => setTwoFactorModal(true)}>Enable</Button></SettingRow>")
L("              <SettingRow label=\"Active sessions\" description=\"1 active session\"><Button variant=\"ghost\" size=\"sm\" onClick={() => setSessionsModal(true)}>Manage</Button></SettingRow>")
L("            </div>")
L("          )}")
L()

# Privacy section
L("          {activeSection === 'privacy' && (")
L("            <div className=\"space-y-1\">")
L("              <h2 className=\"text-base font-semibold mb-4\">Privacy & Search</h2>")
L("              <SettingRow label=\"Profile visibility\" description=\"Who can see your profile\">")
L("                <div className=\"flex gap-1.5\">")
L("                  {(['public','matches','private'] as const).map(v => (")
L("                    <button key={v} onClick={() => updatePref('profileVisibility',v)} className={cn('px-3 py-1.5 rounded-lg text-[11px] font-medium border transition-all', settings.profileVisibility===v ? 'bg-lavender-400/10 border-lavender-400/30 text-lavender-400' : 'border-border text-text-muted')}>{v.charAt(0).toUpperCase()+v.slice(1)}</button>")
L("                  ))}")
L("                </div>")
L("              </SettingRow>")
L("              <SettingRow label=\"Searchable by name\"><Toggle enabled={settings.searchByName} onToggle={() => toggle('searchByName')} /></SettingRow>")
L("              <SettingRow label=\"Searchable by Miamo ID\"><Toggle enabled={settings.searchByMiamoId} onToggle={() => toggle('searchByMiamoId')} /></SettingRow>")
L("              <SettingRow label=\"Searchable by city\"><Toggle enabled={settings.searchByCity} onToggle={() => toggle('searchByCity')} /></SettingRow>")
L("              <SettingRow label=\"Online status\"><Toggle enabled={settings.onlineStatus} onToggle={() => toggle('onlineStatus')} /></SettingRow>")
L("              <SettingRow label=\"Last active\"><Toggle enabled={settings.lastActive} onToggle={() => toggle('lastActive')} /></SettingRow>")
L("              <SettingRow label=\"Read receipts\"><Toggle enabled={settings.readReceipts} onToggle={() => toggle('readReceipts')} /></SettingRow>")
L("              <SettingRow label=\"Typing indicator\"><Toggle enabled={settings.typingIndicator} onToggle={() => toggle('typingIndicator')} /></SettingRow>")
L("              <SettingRow label=\"Serious Mode\"><Toggle enabled={settings.seriousMode} onToggle={() => toggle('seriousMode')} /></SettingRow>")
L("              <SettingRow label=\"Receive broadcasts\"><Toggle enabled={settings.broadcastReceive} onToggle={() => toggle('broadcastReceive')} /></SettingRow>")
L("              <SettingRow label=\"AI personalization\"><Toggle enabled={settings.aiPersonalization} onToggle={() => toggle('aiPersonalization')} /></SettingRow>")
L("            </div>")
L("          )}")
L()

# Notifications section
L("          {activeSection === 'notifications' && (")
L("            <div className=\"space-y-1\">")
L("              <h2 className=\"text-base font-semibold mb-4\">Notifications</h2>")
L("              <SettingRow label=\"Notification sound\"><Toggle enabled={settings.notificationSound} onToggle={() => toggle('notificationSound')} /></SettingRow>")
L("              <SettingRow label=\"Match notifications\"><Toggle enabled={settings.matchNotifications} onToggle={() => toggle('matchNotifications')} /></SettingRow>")
L("              <SettingRow label=\"Message notifications\"><Toggle enabled={settings.messageNotifications} onToggle={() => toggle('messageNotifications')} /></SettingRow>")
L("              <SettingRow label=\"Beat reminders\"><Toggle enabled={settings.beatReminders} onToggle={() => toggle('beatReminders')} /></SettingRow>")
L("              <SettingRow label=\"Story notifications\"><Toggle enabled={settings.storyNotifications} onToggle={() => toggle('storyNotifications')} /></SettingRow>")
L("              <SettingRow label=\"Quiet hours\" description=\"No notifications 11PM\\u20137AM\"><Toggle enabled={settings.quietHours||false} onToggle={() => toggle('quietHours')} /></SettingRow>")
L("            </div>")
L("          )}")
L()

# Appearance section
L("          {activeSection === 'appearance' && (")
L("            <div className=\"space-y-1\">")
L("              <h2 className=\"text-base font-semibold mb-4\">Appearance</h2>")
L("              <SettingRow label=\"Theme\" description={`Current: ${theme.charAt(0).toUpperCase() + theme.slice(1)}`}>")
L("                <div className=\"flex gap-2\">")
L("                  {[{ icon: Moon, label: 'dark' as const }, { icon: Sun, label: 'light' as const }, { icon: Monitor, label: 'system' as const }].map(t => (")
L("                    <button key={t.label} onClick={() => setTheme(t.label)} className={cn('p-2 rounded-lg border transition-all', theme === t.label ? 'bg-lavender-400/10 border-lavender-400/30 text-lavender-400' : 'border-border text-text-muted')}>")
L("                      <t.icon className=\"w-4 h-4\" />")
L("                    </button>")
L("                  ))}")
L("                </div>")
L("              </SettingRow>")
L("              <SettingRow label=\"Font size\" description={`Current: ${settings.fontSize}`}>")
L("                <div className=\"flex gap-1.5\">")
L("                  {[{v:'small',l:'S'},{v:'medium',l:'M'},{v:'large',l:'L'}].map(f => (")
L("                    <button key={f.v} onClick={() => updatePref('fontSize',f.v)} className={cn('w-8 h-8 rounded-lg border flex items-center justify-center text-xs font-bold transition-all', settings.fontSize===f.v ? 'bg-lavender-400/10 border-lavender-400/30 text-lavender-400' : 'border-border text-text-muted')}>{f.l}</button>")
L("                  ))}")
L("                </div>")
L("              </SettingRow>")
L("              <SettingRow label=\"Reduce motion\"><Toggle enabled={settings.reduceMotion} onToggle={() => toggle('reduceMotion')} /></SettingRow>")
L("              <SettingRow label=\"Chat bubble style\">")
L("                <div className=\"flex gap-1.5\">")
L("                  {(['modern','classic','minimal'] as const).map(s => (")
L("                    <button key={s} onClick={() => updatePref('chatBubbleStyle',s)} className={cn('px-3 py-1.5 rounded-lg text-[11px] font-medium border transition-all', settings.chatBubbleStyle===s ? 'bg-lavender-400/10 border-lavender-400/30 text-lavender-400' : 'border-border text-text-muted')}>{s.charAt(0).toUpperCase()+s.slice(1)}</button>")
L("                  ))}")
L("                </div>")
L("              </SettingRow>")
L("              <SettingRow label=\"Accent color\">")
L("                <div className=\"flex gap-1.5\">")
L("                  {['bg-lavender-400','bg-violet-deep','bg-sky-400','bg-emerald-400','bg-amber-400'].map(c => (")
L("                    <div key={c} className={cn('w-5 h-5 rounded-full', c, c === 'bg-lavender-400' && 'ring-2 ring-offset-2 ring-offset-miamo-card ring-lavender-400')} />")
L("                  ))}")
L("                </div>")
L("              </SettingRow>")
L("            </div>")
L("          )}")
L()

# Preferences section (NEW)
L("          {activeSection === 'preferences' && (")
L("            <div className=\"space-y-1\">")
L("              <h2 className=\"text-base font-semibold mb-4\">Preferences</h2>")
L("              <SettingRow label=\"Language\" description={settings.language}>")
L("                <select value={settings.language} onChange={e => updatePref('language', e.target.value)} className=\"bg-miamo-elevated border border-border rounded-lg px-3 py-1.5 text-xs text-text-primary focus:outline-none\">")
L("                  {['English','Hindi','Spanish','French','German','Portuguese','Japanese','Korean','Chinese'].map(l => <option key={l} value={l}>{l}</option>)}")
L("                </select>")
L("              </SettingRow>")
L("              <SettingRow label=\"Auto-play videos\"><Toggle enabled={settings.autoplayVideos} onToggle={() => toggle('autoplayVideos')} /></SettingRow>")
L("              <SettingRow label=\"Date format\">")
L("                <div className=\"flex gap-1.5\">")
L("                  {[{v:'relative',l:'2h ago'},{v:'absolute',l:'May 17'},{v:'short',l:'5/17'}].map(d => (")
L("                    <button key={d.v} onClick={() => updatePref('dateFormat',d.v)} className={cn('px-3 py-1.5 rounded-lg text-[11px] font-medium border transition-all', settings.dateFormat===d.v ? 'bg-lavender-400/10 border-lavender-400/30 text-lavender-400' : 'border-border text-text-muted')}>{d.l}</button>")
L("                  ))}")
L("                </div>")
L("              </SettingRow>")
L("            </div>")
L("          )}")
L()

# Safety section
L("          {activeSection === 'safety' && (")
L("            <div className=\"space-y-1\">")
L("              <h2 className=\"text-base font-semibold mb-4\">Safety</h2>")
L("              <SettingRow label=\"Disappearing messages\" description=\"Auto-delete after 24h\"><Toggle enabled={settings.disappearingMessages} onToggle={() => toggle('disappearingMessages')} /></SettingRow>")
L("              <SettingRow label=\"Block list\" description={`${blockList.length} blocked`}><Button variant=\"ghost\" size=\"sm\" onClick={loadBlockList}>Manage</Button></SettingRow>")
L("              {blockList.length > 0 && (")
L("                <div className=\"space-y-2 py-2\">")
L("                  {blockList.map((b: any) => (")
L("                    <div key={b.id} className=\"flex items-center justify-between bg-miamo-elevated/50 px-3 py-2 rounded-lg\">")
L("                      <span className=\"text-xs text-text-secondary\">{b.displayName || b.username || b.id}</span>")
L("                      <Button variant=\"ghost\" size=\"sm\" onClick={() => handleUnblock(b.id)}>Unblock</Button>")
L("                    </div>")
L("                  ))}")
L("                </div>")
L("              )}")
L("              <SettingRow label=\"Safety tips\"><Button variant=\"ghost\" size=\"sm\" onClick={() => router.push('/safety')}>Read</Button></SettingRow>")
L("            </div>")
L("          )}")
L()

# Data section
L("          {activeSection === 'data' && (")
L("            <div className=\"space-y-1\">")
L("              <h2 className=\"text-base font-semibold mb-4\">Data & Account</h2>")
L("              <SettingRow label=\"Download my data\"><Button variant=\"ghost\" size=\"sm\" onClick={handleDownload} disabled={downloading}><Download className=\"w-3.5 h-3.5\" /> {downloading ? 'Downloading\\u2026' : 'Download'}</Button></SettingRow>")
L("              <SettingRow label=\"Deactivate account\" description=\"Temporarily hide your profile\"><Button variant=\"ghost\" size=\"sm\" onClick={handleDeactivate}>Deactivate</Button></SettingRow>")
L("              <SettingRow label=\"Delete account\" description=\"Permanently delete everything\">")
L("                {showDeleteConfirm ? (")
L("                  <div className=\"flex items-center gap-2\">")
L("                    <span className=\"text-xs text-red-400\">Are you sure?</span>")
L("                    <Button variant=\"danger\" size=\"sm\" onClick={async () => { try { await api.deleteAccount(); clearAuth(); router.push('/login'); } catch { showToast('Failed','error'); } }}>Yes, Delete</Button>")
L("                    <Button variant=\"ghost\" size=\"sm\" onClick={() => setShowDeleteConfirm(false)}>Cancel</Button>")
L("                  </div>")
L("                ) : (")
L("                  <Button variant=\"danger\" size=\"sm\" onClick={() => setShowDeleteConfirm(true)}><Trash2 className=\"w-3.5 h-3.5\" /> Delete</Button>")
L("                )}")
L("              </SettingRow>")
L("              <div className=\"pt-4 border-t border-border/30 mt-4\">")
L("                <p className=\"text-xs text-text-muted\">App version: 1.0.0</p>")
L("                <div className=\"flex gap-3 mt-2 text-xs text-lavender-400\">")
L("                  <a href=\"/safety\" className=\"hover:underline\">Privacy</a>")
L("                  <a href=\"/safety\" className=\"hover:underline\">Terms</a>")
L("                  <a href=\"/safety\" className=\"hover:underline\">Help</a>")
L("                </div>")
L("              </div>")
L("            </div>")
L("          )}")
L("        </Card>")
L("      </div>")
L("      </>)}")
L("    </div>")
L("  );")
L("}")

content = '\n'.join(lines) + '\n'
with open(SETTINGS_PATH, 'w') as f:
    f.write(content)
print(f'Written {len(content)} chars, {len(lines)} lines to {SETTINGS_PATH}')
