#!/usr/bin/env python3
"""
Phase 13 — Creativity reels + Spotlight earn paths (v3.5).

Walks miamo1 (creator) + miamo2 (viewer) through every new endpoint
shipped in v3.5 to confirm:
  • /creativity/reels returns ranked, suppression-aware cards.
  • Daily-login award fires on first reels call of the UTC day for the viewer.
  • /react fires first_beat_sent + beat_received ledger rows.
  • /comments fires first_comment_sent + comment_left ledger rows.
  • /share fires first_share_sent ledger row.
  • /dislike, /not-interested, /report, /hide-author return 200 + suppress
    the offending item/author from the next /reels call.
  • /move-suggestions returns 1..3 lines tagged with a tone.
  • /earn-opportunities returns the full catalog.

Output: scripts/qa-runs/phase-13-creativity-reels.report.json
"""
from __future__ import annotations
import json, os, sys, time, uuid, urllib.request, urllib.error
from collections import Counter
from pathlib import Path

BASE = "http://localhost:3200"
errors: list[dict] = []
sigs: Counter = Counter()


def req(path, method="GET", data=None, token=None, timeout=20, base=BASE):
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = "Bearer " + token
    body = json.dumps(data).encode() if data is not None else None
    for attempt in range(3):
        r = urllib.request.Request(base + path, data=body, headers=headers, method=method)
        try:
            resp = urllib.request.urlopen(r, timeout=timeout)
            raw = resp.read()
            try:
                return json.loads(raw or b"{}"), resp.getcode()
            except json.JSONDecodeError:
                return {"_raw": raw[:400].decode("utf-8", "replace")}, resp.getcode()
        except urllib.error.HTTPError as e:
            body_text = e.read().decode("utf-8", "replace")
            if e.code == 429 and attempt < 2:
                time.sleep(2 ** attempt)
                continue
            try:
                return json.loads(body_text), e.code
            except json.JSONDecodeError:
                return {"_raw": body_text[:400]}, e.code
        except Exception as e:
            return {"_err": str(e)}, 0
    return {"_err": "exhausted"}, 0


def expect(label, code, want, body=None, persona=None):
    if isinstance(want, int):
        want = (want,)
    ok = code in want
    if not ok:
        sig = f"{label} -> {code} (want {sorted(set(want))})"
        sigs[sig] += 1
        errors.append({"persona": persona, "label": label, "code": code, "want": list(want), "body": body})
    return ok


def login(username, password):
    d, c = req("/api/v1/auth/login", "POST", {"email": username + "@miamo.test", "password": password})
    if not expect(f"login/{username}", c, 200, d, username):
        return None
    return (d.get("data") or {}).get("accessToken")


def main():
    # ── Setup: two seeded users ───────────────────────
    tok_creator = login("miamo1", "miamo1")
    tok_viewer = login("miamo2", "miamo2")
    if not tok_creator or not tok_viewer:
        errors.append({"phase": "setup", "msg": "could not login seeded users"})
        sigs["setup login failed"] += 1
        finalize()
        return

    # ── 1. Creator publishes a post in 'Music' ─────────
    item_payload = {
        "category": "Music",
        "type": "text",
        "title": f"Phase13 demo {uuid.uuid4().hex[:6]}",
        "content": "auto-generated by phase-13 regression — safe to ignore",
        "visibility": "everyone",
    }
    d, c = req("/api/v1/creativity/items", "POST", item_payload, token=tok_creator)
    expect("create_item", c, 200, d, "miamo1")
    item_id = (d.get("data") or {}).get("id")
    if not item_id:
        errors.append({"phase": "create_item", "msg": "no id returned", "body": d})
        sigs["create_item missing id"] += 1
        finalize()
        return

    # ── 2. Viewer hits /reels — first call of day awards daily_login ─
    bal_before, _ = req("/api/v1/creativity/spotlight", token=tok_viewer)
    balance_before = ((bal_before.get("data") or {}).get("balance")) or 0

    d, c = req("/api/v1/creativity/reels?limit=5", token=tok_viewer)
    expect("reels_initial", c, 200, d, "miamo2")
    initial_items = d.get("data") or []
    if not isinstance(initial_items, list):
        sigs["reels did not return list"] += 1

    # Daily login is fire-and-forget; allow a small window for the ledger row.
    time.sleep(0.5)
    bal_after, _ = req("/api/v1/creativity/spotlight", token=tok_viewer)
    balance_after = ((bal_after.get("data") or {}).get("balance")) or 0
    if balance_after < balance_before:
        sigs["balance went down after reels call"] += 1
        errors.append({"phase": "daily_login", "before": balance_before, "after": balance_after})

    # ── 3. /react (beat) → first_beat_sent + beat_received ─
    d, c = req(f"/api/v1/creativity/items/{item_id}/react", "POST", {"type": "like"}, token=tok_viewer)
    expect("react_like", c, 200, d, "miamo2")

    # ── 4. /comment → first_comment_sent + comment_left ──
    d, c = req(f"/api/v1/creativity/items/{item_id}/comments", "POST", {"content": "phase-13 auto comment"}, token=tok_viewer)
    expect("comment_create", c, 200, d, "miamo2")

    # ── 5. /share → first_share_sent ──────────────────
    d, c = req(f"/api/v1/creativity/items/{item_id}/share", "POST", {"channel": "phase13"}, token=tok_viewer)
    expect("share", c, 200, d, "miamo2")

    # ── 6. /move-suggestions → 1..3 suggestions ─────
    d, c = req(f"/api/v1/creativity/items/{item_id}/move-suggestions?n=3", token=tok_viewer)
    expect("move_suggestions", c, 200, d, "miamo2")
    suggestions = ((d.get("data") or {}).get("suggestions")) or []
    if not (isinstance(suggestions, list) and 1 <= len(suggestions) <= 3):
        sigs[f"move-suggestions returned {len(suggestions)} items (want 1..3)"] += 1
        errors.append({"phase": "move_suggestions", "got": suggestions})
    for s in suggestions:
        if not isinstance(s, dict) or "line" not in s or "tone" not in s:
            sigs["move-suggestion missing tone/line"] += 1

    # ── 7. /earn-opportunities ────────────────────────
    d, c = req("/api/v1/creativity/spotlight/earn-opportunities", token=tok_viewer)
    expect("earn_opps", c, 200, d, "miamo2")
    opps = ((d.get("data") or {}).get("opportunities")) or []
    expected_kinds = {"daily_login", "comment_left", "beat_received", "profile_100",
                      "streak_7d_creativity", "first_beat_sent", "first_comment_sent",
                      "first_share_sent", "matches_10", "weekly_top_creator"}
    got_kinds = {o.get("kind") for o in opps if isinstance(o, dict)}
    missing = expected_kinds - got_kinds
    if missing:
        sigs[f"earn-opportunities missing kinds: {sorted(missing)}"] += 1
        errors.append({"phase": "earn_opps", "missing": sorted(missing), "got": sorted(got_kinds)})

    # ── 8. /dislike → item is suppressed from next reels ─
    # Need a fresh item that isn't from the suppressed author yet.
    other_payload = {**item_payload, "title": f"Phase13 dislike target {uuid.uuid4().hex[:6]}"}
    d, c = req("/api/v1/creativity/items", "POST", other_payload, token=tok_creator)
    expect("create_dislike_target", c, 200, d, "miamo1")
    dislike_id = (d.get("data") or {}).get("id")
    if dislike_id:
        d, c = req(f"/api/v1/creativity/items/{dislike_id}/dislike", "POST", token=tok_viewer)
        expect("dislike", c, 200, d, "miamo2")
        # Now confirm next reels call does NOT include dislike_id.
        d, c = req("/api/v1/creativity/reels?limit=20", token=tok_viewer)
        expect("reels_after_dislike", c, 200, d, "miamo2")
        ids = {it.get("id") for it in (d.get("data") or []) if isinstance(it, dict)}
        if dislike_id in ids:
            sigs["dislike did not suppress item"] += 1
            errors.append({"phase": "dislike_suppress", "item_id": dislike_id})

    # ── 9. /not-interested ───────────────────────────
    ni_payload = {**item_payload, "title": f"Phase13 NI {uuid.uuid4().hex[:6]}"}
    d, c = req("/api/v1/creativity/items", "POST", ni_payload, token=tok_creator)
    ni_id = (d.get("data") or {}).get("id")
    if ni_id:
        d, c = req(f"/api/v1/creativity/items/{ni_id}/not-interested", "POST", {"reason": "test"}, token=tok_viewer)
        expect("not_interested", c, 200, d, "miamo2")

    # ── 10. /report ────────────────────────────────
    rep_payload = {**item_payload, "title": f"Phase13 RPT {uuid.uuid4().hex[:6]}"}
    d, c = req("/api/v1/creativity/items", "POST", rep_payload, token=tok_creator)
    rep_id = (d.get("data") or {}).get("id")
    if rep_id:
        d, c = req(f"/api/v1/creativity/items/{rep_id}/report", "POST", {"reason": "phase13 auto-report"}, token=tok_viewer)
        expect("report", c, 200, d, "miamo2")

    # ── 11. /hide-author ───────────────────────────
    ha_payload = {**item_payload, "title": f"Phase13 HA {uuid.uuid4().hex[:6]}"}
    d, c = req("/api/v1/creativity/items", "POST", ha_payload, token=tok_creator)
    ha_id = (d.get("data") or {}).get("id")
    if ha_id:
        d, c = req(f"/api/v1/creativity/items/{ha_id}/hide-author", "POST", token=tok_viewer)
        expect("hide_author", c, 200, d, "miamo2")
        # Next reels call must not contain ANY items from miamo1.
        d, c = req("/api/v1/creativity/reels?limit=20", token=tok_viewer)
        expect("reels_after_hide_author", c, 200, d, "miamo2")
        author_ids = {(it.get("author") or {}).get("id") for it in (d.get("data") or []) if isinstance(it, dict)}
        # We don't know miamo1's id by token alone — fetch a discoverable trace via shared item author from earlier.
        # If miamo1 has any item left in the slice we'd see it; the assertion is "no items from this author."
        # Cross-check using the item we DID create from miamo1: re-fetch it and grab author id.
        d2, _ = req(f"/api/v1/creativity/items?category=Music", token=tok_viewer)
        candidates = (d2.get("data") or [])
        miamo1_id = None
        for it in candidates:
            if (it.get("author") or {}).get("username") == "miamo1":
                miamo1_id = (it.get("author") or {}).get("id"); break
        if miamo1_id and miamo1_id in author_ids:
            sigs["hide_author did not suppress author"] += 1
            errors.append({"phase": "hide_author_suppress", "authorId": miamo1_id, "in_reels": True})

    # ── 12. /claim-streak (best-effort; usually not yet eligible) ─
    d, c = req("/api/v1/creativity/spotlight/claim-streak", "POST", token=tok_viewer)
    expect("claim_streak", c, 200, d, "miamo2")

    finalize()


def finalize():
    out = {
        "phase": "13_creativity_reels",
        "base": BASE,
        "total_events": len(errors),
        "signatures": dict(sigs),
        "events": errors[:50],
    }
    report = Path(__file__).resolve().parent / "phase-13-creativity-reels.report.json"
    report.write_text(json.dumps(out, indent=2))
    summary = f"phase-13: {len(errors)} events, {len(sigs)} signatures"
    print(summary)
    print(json.dumps(dict(sigs), indent=2))
    sys.exit(0 if len(errors) == 0 else 1)


if __name__ == "__main__":
    main()
